{% set version = "2.5.0" %}
{% set number = "5" %}

package:
  name: pymol-open-source
  version: {{ version }}

source:
  url: https://github.com/schrodinger/pymol-open-source/archive/v{{ version }}.tar.gz
  sha256: aa828bf5719bd9a14510118a93182a6e0cadc03a574ba1e327e1e9780a0e80b3

build:
  number: {{ number }}
  script: {{ PYTHON }} setup.py install --use-msgpackc=no --no-libxml
  skip: true  # [py < 37]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}        # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
    - {{ cdt('libxext') }}           # [linux]
  host:
    - python
    - numpy
    - pip
    - glew
    - libglu                         # [linux]
    - libpng
    - freetype
    - glm
    - xorg-libxfixes
    - libnetcdf
  run:
    - python
    - {{ pin_compatible("numpy") }}
    - {{ pin_compatible("libnetcdf") }}
    - libpng
    - freetype
    - pyqt
    - glm
    - pmw

test:
  requires:
    - requests
  files:
    - test.py
  commands:
    - python test.py

app:
  entry: pymol
  summary: PyMOL molecular visualization system

about:
  home: https://pymol.org/
  license: LicenseRef-PyMOL
  license_file: LICENSE.txt
  summary: A user-sponsored molecular visualization system. PyMOL is a trademark of Schrodinger, LLC.
  description: |
    PyMOL is a molecular visualization software with a Python based command line.
    This is a user-created build based on the open-source variant of the PyMOL software.
    PyMOL is a trademark of Schrodinger, LLC.
  doc_url: https://pymolwiki.org/
  dev_url: https://github.com/schrodinger/pymol-open-source/

extra:
  recipe-maintainers:
    - padix-key
    - awacha
    - bkpoon
